apiVersion: batch/v1
kind: CronJob
metadata:
  name: sleepy
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 10
      template:
        spec:
          containers:
            - name: sleepy
              image: busybox
              command: [ "/bin/sleep" ]
              args: [ "30" ]
          restartPolicy: Never
