apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-default
spec:
  podSelector: { }
  policyTypes:
    - Ingress
    #- Egress
  ingress:
    - from:
        - podSelector: { }
      ports:
        - protocol: TCP
          port: 80



